### ISSUE TITLE
Unable to handle "tax_related" field

### ISSUE THREAD

**Issue by zoagold95** [isaacharrisholt/quiffen#88]
When using Qif.parse() on a .qif file that has been exported from MoneyDance, it would appear that there is not a 'tax_related' field. And when you try to parse the file you get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/quiffen/core/qif.py", line 195, in parse
    new_category = Category.from_list(sanitised_section_lines)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/quiffen/core/category.py", line 468, in from_list
    new_cat = cls(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Category
tax_related
  value could not be parsed to a boolean (type=type_error.bool)`
  
I opened the file in TextEditor, and did a search for the word 'tax' and it does not exist in the file at all.

**Comment by isaacharrisholt** [comment]
Sorry for the late response. Could you send an example of the QIF file used?

**Comment by isaacharrisholt** [comment]
Closing due to inactivity and lack of time. If anyone runs into this again, please reopen and submit a PR!
