### ISSUE TITLE
(Documentation ticket) "ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject"

### ISSUE THREAD

**Issue by DreadPirateShawn** [isaacharrisholt/quiffen#91]
## Bug repro

Repro using the "test.qif" from this repo:
```
from quiffen import Qif
qif = Qif.parse('qif/test.qif', day_first=False)
print(qif.accounts)
```

```
(.venv) [user@box mydir]$ python3 process.py 
Traceback (most recent call last):
  File "mydir/process.py", line 1, in <module>
    from quiffen import Qif
  File "mydir/.venv/lib/python3.12/site-packages/quiffen/__init__.py", line 18, in <module>
    from quiffen.core.qif import ParserException, Qif, QifDataType
  File "mydir/.venv/lib/python3.12/site-packages/quiffen/core/qif.py", line 21, in <module>
    import pandas as pd
  File "mydir/.venv/lib/python3.12/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mydir/.venv/lib/python3.12/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "mydir/.venv/lib/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "mydir/.venv/lib/python3.12/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "mydir/.venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "mydir/.venv/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

## Workaround

```
pip3 install numpy==1.26.4
```
or
```
pip3 install "numpy<2"
```

Reference: https://github.com/numpy/numpy/issues/26710

## Suggested fix

This might be worth adding as a documentation note in the README. That said, the existence of this ticket might also serve as documentation enough.

**Comment by danizen** [comment]
If the goal is to export to a pandas DataFrame, then the objective should be that the export works where pandas dataframes would be expected - an ipython shell or Jupyter notebook.  I think this needs a better fix than that, because pandas 1.x and numpy 1.x are quite old and this doesn't match with the ecosystem.  If I want to use ipython, ipdb, or Jupyter notebook/lab with quiffen, I will be out of luck.

**Comment by DavidGeorge528** [comment]
PR #105 migrates the project to UV, during the migration the version range of numpy, pandas and pydantic were set to fix issues like this PR, but also set the upper-bound to the current latest version of each project, as this project is compatible with each of them

The lower bound of pandas is set to V2, however, numpy and pydantic are still V1 as there is a substantial refactor required to migrate from pydantic v1 to v2.

This should allow you to use quiffen with pandas v2, numpy v2 and pydantic v2
