### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pschatzmann** [isaacharrisholt/quiffen#99]
Could you pin the numpy version to something which is working, or even better make sure that an actual pandas version is supported.

I am getting the following error:

```
pip install quiffen
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: quiffen in /home/pschatzmann/.local/lib/python3.10/site-packages (2.0.13)
Requirement already satisfied: pandas<2.0.0,>=1.5.1 in /home/pschatzmann/.local/lib/python3.10/site-packages (from quiffen) (1.5.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /home/pschatzmann/.local/lib/python3.10/site-packages (from quiffen) (2.9.0.post0)
Requirement already satisfied: pydantic<2.0.0,>=1.10.2 in /home/pschatzmann/.local/lib/python3.10/site-packages (from quiffen) (1.10.19)
Requirement already satisfied: numpy>=1.21.0 in /home/pschatzmann/.local/lib/python3.10/site-packages (from pandas<2.0.0,>=1.5.1->quiffen) (2.2.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas<2.0.0,>=1.5.1->quiffen) (2022.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/pschatzmann/.local/lib/python3.10/site-packages (from pydantic<2.0.0,>=1.10.2->quiffen) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3.0.0,>=2.8.2->quiffen) (1.16.0)
(quiffen) pschatzmann@air-mini:~/Downloads$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
(quiffen) pschatzmann@air-mini:~/Downloads$ python3
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from quiffen import Qif, QifDataType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/quiffen/__init__.py", line 18, in <module>
    from quiffen.core.qif import ParserException, Qif, QifDataType
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/quiffen/core/qif.py", line 21, in <module>
    import pandas as pd
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/pschatzmann/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by lcmcninch** [comment]
I encountered the same issue. I was able to resolve it by manually pip-installing pandas version 2.2.3. But it would be great if the quiffen dependencies were set up to pip install and run successfully. I looked into making the change myself but it looks like the project uses poetry for dependency management and I'm not familiar with that tool. @isaacharrisholt if there's anything I can do to help resolve this issue, please let me know.

**Comment by isaacharrisholt** [comment]
Thanks for raising. I'm aware this is a problem, but last time I looked into it, I had some trouble getting the Tox tests working on Python 13, and I didn't spend much time investigating.

@lcmcninch I'm more than happy for you to look into this. Poetry is fairly straightforward: https://python-poetry.org/

That said, I'd also be keen to a see a PR porting Quiffen to use uv, as that seems to be the standard these days. Unfortunately I don't have huge amounts of time to dedicate to this project at the moment.

**Comment by lcmcninch** [comment]
@isaacharrisholt Actually I'd also be interested in learning uv. No guarantees on time, but I'll take a look at it. If I can work it out, I'll submit a PR for that and make sure that this issue is addressed too.

**Comment by isaacharrisholt** [comment]
@lcmcninch sounds like a plan, thank you!

**Comment by DavidGeorge528** [comment]
Hey, found this project a few days ago and was having similar issues to ones posted here, so I made some changes to move the package to UV, pin pandas and numpy to newer versions and ensure all the tests run before the PR was posted. It's up now, any comments welcome!
